### ISSUE TITLE
Last version (1.0.5) not in PyPI

### ISSUE THREAD

**Issue by ygneo** [tr4cefl0w/virustotal3#1]
Hi.

I am going to use this client library, and it looks like last version (1.0.5) is not in PyPI yet:
https://pypi.org/project/virustotal3/

Would you mind to update it?

Thanks.

**Comment by traceflow** [comment]
Hey,

I tried to but my phone broke a few weeks ago and PyPI doesn't provide any way to recover an account that had 2FA enable. They have yet to support recovery codes; see https://github.com/pypa/warehouse/issues/5800

You can either add it to your `requirements.txt` using `git+https://github.com/tr4cefl0w/virustotal3` or wait until I create a new PyPI account and re-upload everything. But before I do that, I'm trying to see if there's a way they could delete the account so I can re-create it.

Sorry for the trouble.

**Comment by ygneo** [comment]
Ok, no problem.

 Would you mind to keep this issue open so you can ping me here when you have been able to either recover or recreate your account?

Thanks.

**Comment by traceflow** [comment]
Sure no problem

**Comment by traceflow** [comment]
I'm planning on adding some new features in the coming weeks/months and there's no way I can recover my 2FA on PyPI at the moment so I will create a new PyPI package soon and update the README.

**Comment by traceflow** [comment]
The latest version is uploaded to pypi
