### ISSUE TITLE
potential exposed api token

### ISSUE THREAD

**Issue by helldrum** [tr4cefl0w/virustotal3#12]
https://github.com/tr4cefl0w/virustotal3/blob/454be5716987471d2229dc2434b4084c84d7e4ec/examples/download.py#L6

**Comment by helldrum** [comment]
i guess you revoke this token but just in case you are not aware of this

**Comment by helldrum** [comment]
same here

examples/add_comment.py:17:vt.add_comment('**************************************', comment)
examples/get_votes.py:17:votes = vt.get_votes('**************************************')
examples/get_relationship.py:8:relationship = vt.get_relationships('**************************************',
examples/download.py:6:vt.download('**************************************', '~/samples')

**Comment by traceflow** [comment]
This is a file hash, not an API key.
