### ISSUE TITLE
`virustotal3.enterprise.file_feed()` broken

### ISSUE THREAD

**Issue by xaocon** [tr4cefl0w/virustotal3#4]
I don't know if this worked at one point and the API changed or what but it redirects to a bz2 file now and requests seems to handle it transparently. Returning `.json()` causes and exception because the bz2 file can't be parsed as json.

**Comment by traceflow** [comment]
Looks like there was a change in the API on VirusTotal's side. I'll look into it and make the necessary changes next week probably. Thanks for reporting.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by xaocon** [comment]
You might update the docs while you're there as well. Looks like packages must be an hour old before they are downloadable instead of 5 minutes. Thanks for being so responsive. If you know how you want it to work already I'm pretty open to submitting a PR.

**Comment by xaocon** [comment]
ohh, also, it looks like a 404 shouldn't be treated as an exception every time now.

**Comment by traceflow** [comment]
Sure, pull requests are more than welcome as I'm short on time these days to work on this, especially with the current pandemic.

Thanks for the help!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by traceflow** [comment]
Hey, unfortunately I no longer have access to file feed. It's a separate feature from the standard Enterprise subscription. If you or someone else could fix it, it'd be appreciated, otherwise I might remove it to avoid further issues to be opened. I must have misread the documentation on this one, I just had a look. You're right that it should return a bzip2. Thanks

**Comment by xaocon** [comment]
I can put in an MR if you want. If you know that you want it to work a certain way already then let me know. Otherwise I'll just do what seems to make the most sense to me.
